name: Release

on:
  push:
    tags: [v*.*.*]

jobs:
  publish:
    name: Publish server docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: docker_meta
        name: Docker meta
        uses: docker/metadata-action@v4
        with:
          images: agnjunio/albion-killbot
          tag: type=semver,pattern={{version}}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: server/
          push: ${{ github.event_name != 'pull_request' }}
          file: server/docker/Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
